{-# OPTIONS_GHC -O2 -Wall -fwarn-tabs -fdefer-typed-holes #-}


-- automatically generated by BNF Converter
module Main where


import System.IO ( stderr, hPutStrLn )
import System.Environment ( getArgs )
import DynamicGrammar

import ErrM


-- TODO maybe use verbosity of error messages
type Verbosity = Int

main :: IO ()
main = do
  [fileName] <- getArgs
  file <- readFile fileName

  case parse file >>= desugar_prog of
    Bad err -> do
      hPutStrLn stderr "Compilation error:"
      hPutStrLn stderr err
    Ok expr -> do
      case interpret expr of
        Ok (EVal value) ->
          putStrLn $ show value
        Ok expr -> do
          hPutStrLn stderr "Bad return value"
          hPutStrLn stderr $ indent expr
        Bad err -> do
          hPutStrLn stderr "Runtime error: "
          hPutStrLn stderr err
          hPutStrLn stderr $ indent expr




