{-# OPTIONS_GHC -O2 -Wall -fwarn-tabs -fdefer-typed-holes #-}


-- automatically generated by BNF Converter
module Main where


import System.IO ( stderr, hPutStrLn )
import System.Environment ( getArgs )

import DynGrammar
import Compile
import Err
import Exp
import Util

-- TODO maybe use verbosity of error messages
type Verbosity = Int

main :: IO ()
main = do
  [fileName] <- getArgs
  file <- readFile fileName

  case parse file >>= desugarProg of
    Bad err -> do
      hPutStrLn stderr "Compilation error:"
      hPutStrLn stderr $ show err
    Ok expr -> do
      case interpret expr of
        Ok final -> do
          putStrLn $ show final
        Bad err -> do
          hPutStrLn stderr "Runtime error: "
          hPutStrLn stderr $ show err
          hPutStrLn stderr $ indent expr
